In [1]:
pip install pyspark

Collecting pyspark
  Downloading https://files.pythonhosted.org/packages/45/b0/9d6860891ab14a39d4bddf80ba26ce51c2f9dc4805e5c6978ac0472c120a/pyspark-3.1.1.tar.gz (212.3MB)
     |████████████████████████████████| 212.3MB 60kB/s
Collecting py4j==0.10.9
  Downloading https://files.pythonhosted.org/packages/9e/b6/6a4fb90cd235dc8e265a6a2067f2a2c99f0d91787f06aca4bcf7c23f3f80/py4j-0.10.9-py2.py3-none-any.whl (198kB)
     |████████████████████████████████| 204kB 53.6MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.1.1-py2.py3-none-any.whl size=212767604 sha256=c30db4186b900063c03282e39f0966f6c5b9c490ceb8d465a57c6a6f9915e526
  Stored in directory: /root/.cache/pip/wheels/0b/90/c0/01de724414ef122bd05f056541fb6a0ecf47c7ca655f8b3c0f
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9 pyspark-3.1.1

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("Bank project").getOrCreate()

In [6]:
df = spark.read.csv("/content/drive/MyDrive/Colab Notebooks/bank.csv",header=True,inferSchema=True)
df.printSchema()

AnalysisException: ignored

In [ ]:
from pyspark.ml.feature import StringIndexer
indexer = StringIndexer()
indexer.setInputCol("job").setOutputCol("job_index")
df1 = indexer.fit(df).transform(df)

In [ ]:
df1.toPandas()

In [ ]:
indexer.setInputCol("marital").setOutputCol("marital_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("education").setOutputCol("education_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("default").setOutputCol("default_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("housing").setOutputCol("housing_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("loan").setOutputCol("loan_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("contact").setOutputCol("contact_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("month").setOutputCol("month_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("poutcome").setOutputCol("poutcome_index")
df1 = indexer.fit(df1).transform(df1)
indexer.setInputCol("deposit").setOutputCol("deposit_index")
df1 = indexer.fit(df1).transform(df1)

In [ ]:
df1.toPandas()

       age          job  marital  ... month_index poutcome_index  deposit_index
0       59       admin.  married  ...         0.0            0.0            1.0
1       56       admin.  married  ...         0.0            0.0            1.0
2       41   technician  married  ...         0.0            0.0            1.0
3       55     services  married  ...         0.0            0.0            1.0
4       54       admin.  married  ...         0.0            0.0            1.0
...    ...          ...      ...  ...         ...            ...            ...
11157   33  blue-collar   single  ...         5.0            0.0            0.0
11158   39     services  married  ...         3.0            0.0            0.0
11159   32   technician   single  ...         1.0            0.0            0.0
11160   43   technician  married  ...         0.0            1.0            0.0
11161   34   technician  married  ...         2.0            0.0            0.0

[11162 rows x 27 columns]